Transactions
youmari/vet_clinic pull request #2
Opened 2022-02-15 23:07 UTC by youmari

## In this branch I did the following : 
- Update  and Delete records safely 
- Add species column to the table animals 
- Perform  transactions
- Add queries using aggregate functions and group by

2022-02-15 23:17 UTC, mmsesay requested changes
Hi @youmari , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 23:17 UTC, mmsesay commented on queries.sql
> +SELECT species, AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-01-01' GROUP BY species;
- [ ] You did well writing these queries. However, you need to implement transaction queries as well, just as stated in main bullet points 4 & 5 of the [project requirement](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md)

2022-02-15 23:53 UTC, youmari commented on queries.sql
> +SELECT species, AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-01-01' GROUP BY species;
thanks for your feedback just a misconception happened

2022-02-16 00:09 UTC, DammyShittu requested changes
Hi @youmari, 

Great work on making the changes requested by a previous reviewer 👏
 
You've done well implementing some of the requested changes, but there are still a tiny part that hasn't been addressed yet.

 ## Required Changes ♻️

_Check the comment under the review._

## Optional suggestions

- I can see that you're currently hard coding the `id` of each record/row being added. I would suggest that you add the `GENERATED ALWAYS AS IDENTITY` constraint to the `id` column. This will help you to generate sequential integers that cannot be altered when the record is being created.
You can go through this [guide](https://www.sqltutorial.org/sql-identity/#:~:text=The%20GENERATED%20ALWAYS%20generates%20sequential,integers%20for%20the%20identity%20column.) for more details. 😉 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 00:09 UTC, DammyShittu commented on queries.sql
> +\d animals;
- Kindly `UPDATE` the `animals` table and `SET` the `species` equal to 'unspecified' as the requirement says. 😉

![](https://i.imgur.com/pTQel6T.png)

2022-02-16 00:14 UTC, youmari commented on queries.sql
> +\d animals;
@DammyShittu Hey that's what line 21 do it's update the species to unspecified

2022-02-16 00:20 UTC, youmari commented
sorry by mistake I deleted the comment @DammyShittu

2022-02-16 00:22 UTC, DammyShittu commented
> sorry by mistake I deleted the comment @DammyShittu

Hi @youmari,
The query on line 21 will change the column name from `species` to `unspecified`. However, that is not what was mentioned in the project requirement as seen in the screenshot above ☝️.

The `species` column for each row should read `unspecified` after executing the query and not change the column name to `unspecified`.

The correct query should look like this 👇 

```
UPDATE animals
   SET species = 'unspecified'; 
```

I hope this helps. 😃

2022-02-16 00:45 UTC, youmari commented
okay I got it

2022-02-16 00:49 UTC, DammyShittu approved these changes
Hi @youmari, 

## APPROVED 🟢 

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 00:50 UTC, merged